name: workflowrun

on:
  workflow_run:
    workflows: [rebase]
    types:
      - completed

jobs:
  do-thin:
    runs-on: ubuntu-20.04
    name: adsfadsf

    steps:
      - name: Print
        env:
          HELLO: ${{ toJSON(github.event) }}
        run: |
          echo "asdfasdf"
          echo $HELLO
