name: workflowrun

on:
  workflow_run:
    workflows: [rebase]
    types:
      - completed

jobs:
  do-thin:
    if: github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == 'failure'
    runs-on: ubuntu-20.04
    name: adsfadsf

    steps:
      - name: Print
        env:
          HELLO: ${{ toJSON(github) }}
        run: |
          echo "asdfasdf"
          echo $HELLO
