name: rebase

on:
  repository_dispatch:
  issue_comment:
    types: [created]
  push:

jobs:
  do_rebase:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup committer id
        continue-on-error: true
        run: |
          echo "asdfasdf"
