name: Rebase PR

on:
  repository_dispatch:
  issue_comment:
    types: [created]

jobs:
  do_rebase:
    if: contains(github.event.comment.body, '/rebase')
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Setup committer id
        run: |
          git config --global user.email "csl@fb.com"
          git config --global user.name "Catherine Lee"

      - name: Rebase
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          PR_NUM: ${{ github.event.client_payload.pr_num }}
          GH_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          BRANCH: ${{ github.event.client_payload.branch }}
        run: |
          set -ex
          if [ -n "${BRANCH}" ]; then
            python3 tryrebase.py 15 --branch "{BRANCH}"
          else
            python3 tryrebase.py 15
          fi
