name: Rebase PR

on:
  repository_dispatch:
  issue_comment:
    types: [created]
  push:

jobs:
  do_rebase:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Setup committer id
        continue-on-error: true
        run: |
          zip a.zip 'dslkfajdslkfj'
